### ISSUE TITLE
Compare with `scc::HashMap`?

### ISSUE THREAD

**Issue by PsiACE** [jonhoo/griddle#16]
[wvwwvwwv/scc](https://github.com/wvwwvwwv/scc/)  offers scalable concurrent containers, and it has smaller (1/20?) spikes. What do you think of this?

```
hashbrown::HashMap max: 65.076781ms, mean: 184ns
griddle::HashMap max: 2.564017ms, mean: 219ns
scc::HashMap max: 108.514µs, mean: 543ns
```

In addition, thank you very much for your contribution. I have used griddle in my key-value pair store implementation - [ritedb/ritekv](https://github.com/ritedb/ritekv).

**Comment by PsiACE** [comment]
```
use griddle::HashMap as IncrHashMap;
use scc::HashMap as SccHashMap;
use hashbrown::HashMap;
use std::time::{Duration, Instant};
use std::collections::hash_map::RandomState;

const N: u32 = 1 << 22;

fn main() {
    let mut hm = HashMap::new();
    let mut mx = 0.0f64;
    let mut sum = Duration::new(0, 0);
    for i in 0..N {
        let t = Instant::now();
        hm.insert(i, i);
        let took = t.elapsed();
        mx = mx.max(took.as_secs_f64());
        sum += took;
        println!("{} hashbrown {} ms", i, took.as_secs_f64() * 1000.0);
    }
    eprintln!(
        "hashbrown::HashMap max: {:?}, mean: {:?}",
        Duration::from_secs_f64(mx),
        sum / N
    );

    let mut hm = IncrHashMap::new();
    let mut mx = 0.0f64;
    let mut sum = Duration::new(0, 0);
    for i in 0..N {
        let t = Instant::now();
        hm.insert(i, i);
        let took = t.elapsed();
        mx = mx.max(took.as_secs_f64());
        sum += took;
        println!("{} griddle {} ms", i, took.as_secs_f64() * 1000.0);
    }
    eprintln!(
        "griddle::HashMap max: {:?}, mean: {:?}",
        Duration::from_secs_f64(mx),
        sum / N
    );
    
    let hm = SccHashMap::new(0, RandomState::new());
    let mut mx = 0.0f64;
    let mut sum = Duration::new(0, 0);
    for i in 0..N {
        let t = Instant::now();
        hm.insert(i, i);
        let took = t.elapsed();
        mx = mx.max(took.as_secs_f64());
        sum += took;
        println!("{} scc {} ms", i, took.as_secs_f64() * 1000.0);
    }
    eprintln!(
        "scc::HashMap max: {:?}, mean: {:?}",
        Duration::from_secs_f64(mx),
        sum / N
    );
}
```

**Comment by jonhoo** [comment]
Hmm, that's interesting. `scc` seems to be a concurrent map, not a single-threaded one, so we _should_ be able to do much better here. I wonder where their wins related to this specifically come from.. Given the 2-3x higher average insertion cost (don't know about gets?), I think it probably wouldn't make sense to prefer `scc` over `griddle` in most workloads, though it's hard to say for sure. As always with these things, the answer lies in benchmarking your application. I don't think a simple benchmark will actually do the true trade-offs justice.

I think `scc` is probably something that should be compared to `dashmap` or `flurry`, rather than `griddle`.

**Comment by PsiACE** [comment]
I’m sorry I didn’t respond sooner. 
Thank you for your comments. In fact, I was just wondering how it got the peak down so much. 
I think I can close the issue.
